### PR TITLE
Update 02-think-data.md with new task

### PR DESCRIPTION
**Pull request by jamieviva**
Made a very slight grammatical correction to the previous task and appended an additional task.

### CODE REVIEW

**Comment by drjwbaker** [comment]
Thanks for the fix and suggestion @jamieviva. My only qualm is how this is presented: is it here as an either/or with the other task? Or is it an additional task? If the latter we need to change the exercise time part of the file. Before we proceed - and I'm happy to make the necessary changes rather than leaving you to do all the work - what was your intention in this regard?

@JennyBunn + @ngeraci: what I say above not withstanding, I like this and am happy to proceed. Agreed?

**Comment by ngeraci** [comment]
agree with @drjwbaker on all counts-- I think the new task is great, but want to clarify how it fits in. If the idea is to use both, should we perhaps condense the first task?

I could also see just using the second task and removing the first (and change line 34 to something more general about identifying data to use as an example). The first task still feels very researcher-oriented, while I think the second one is a better fit for archivists.

**Comment by JennyBunn** [comment]
Thanks @jamieviva I think this could work well, with the clarification suggested by @drjwbaker. 

I do disagree slightly with @ngeraci though. The second one is possibly a better fit for archivists, but that could be an issue. With its talk of data lifecycles it places them firmly in their comfort zone and implies their more usual passive role as custodians of other people's data. Part of the purpose of the first task is to shake them out of that a little and to get them to see themselves as active users/manipulators of data. For this reason I think I would go for an either/or, or an additional task, rather than a one or the other. We could try both out at the Library Carpentry day at The National Archives in November and see what the participants say?

**Comment by drjwbaker** [comment]
> We could try both out at the Library Carpentry day at The National Archives in November and see what the participants say?

@JennyBunn: good idea.

**Comment by drjwbaker** [comment]
For now, add some text and then merge as an either/or?

**Comment by jamieviva** [comment]
@drjwbaker @ngeraci @jennybunn thanks for your feedback - my intention was that this task follow the preceeding task, but it could also be an either/or. The aim of the task is to encourage archivists to think about archival data abstracted from the systems it lives in and to think about how archival data, especially metadata, might have value outside of an archival context (I think a good example would be rights metadata).

**Comment by drjwbaker** [comment]
@jamieviva Okay. In which case we'd need to adjust the timings a little and add some text. I can do this - hopefully today - then leave for @ngeraci or @JennyBunn to approve the PR.

**Comment by jamieviva** [comment]
@drjwbaker Great, let me know if there's anything I can do to help.

**Comment by drjwbaker** [comment]
@jamieviva @ngeraci @JennyBunn: patched. If happy, merge.

**Comment by JennyBunn** [comment]
@drjwbaker @ngeraci @jamieviva Thanks all and happy to merge, if someone tells me how to do that. I am getting a message at the moment which implies I can't do this because I do not have write access?

**Comment by drjwbaker** [comment]
@JennyBunn Merged (and I've given you admin permissions: see your email)

**Pull request merged**
